### ISSUE TITLE
Files without payload disappears after reboot

### ISSUE THREAD

**Issue by umlsynco** [electricimp/SPIFlashFileSystem#20]
An empty file doesn't store on the flash and disappear after reboot:

Example:
hardware.sffs.open("test1.txt", "w").close(); // an empty file

**Comment by blindman2k** [comment]
This isn't a bug, it's a design choice :)
If there is consensus on changing that behaviour ... comment here.

**Comment by umlsynco** [comment]
I suppose that we should add such design choice into the README documentation.

**Comment by ppetrosh** [comment]
Should have been fixed with https://github.com/electricimp/SPIFlashFileSystem/pull/23
