### ISSUE TITLE
There is no exception throw on a File.seek for a wrong position

### ISSUE THREAD

**Issue by umlsynco** [electricimp/SPIFlashFileSystem#21]
It is possible to seek for a length which is more then file size:

there is no exception on:
file.seek(file.len() + 10);

and after that  "file.tell(); " return position which is equal to the (file.len() + 10)

**Comment by blindman2k** [comment]
@umlsynco, can you submit a pull request changing that behaviour?

**Comment by ppetrosh** [comment]
Should have been fixed with https://github.com/electricimp/SPIFlashFileSystem/pull/23
