### ISSUE TITLE
It is possible to keep on reading file after close

### ISSUE THREAD

**Issue by umlsynco** [electricimp/SPIFlashFileSystem#22]
For example:

local file = hardware.sffs.open("file.txt", "r");
local payload = file.read(10);
file.close();

// expect that there is no way to seek and read after close, but the following code works:
file.seek(0);
local payload2 = file.read(10);

**Comment by blindman2k** [comment]
That's actually a simple fix of adding the status in the file class and throwing an exception if the status is closed. @umlsynco, would you like to submit a fix?

**Comment by ppetrosh** [comment]
Should have been fixed with https://github.com/electricimp/SPIFlashFileSystem/pull/23
