### ISSUE TITLE
Two separate instances of SFFS

### ISSUE THREAD

**Issue by ragrus-nbl** [electricimp/SPIFlashFileSystem#29]
It looks like it is possible to create and use two separate instances of SFFS in parallel. And it's a normal case, I believe.
But technically, there is an issue with parallel usage of multiple SFFSs: the garbage collector can be run asynchronously (and automatically). It calls [_enable()](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L637) at the beginning and then does its work in async mode (imp.wakeup). After that, it calls  [_disable()](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L643) once the work is done. The problem is the following: if one instance of SFFS is running its garbage collector (async) and another instance is processing some operation requiring enabling and disabling of the flash (e.g. eraseAll()) before that GC finished, the operation of the latter instance will disable the flash and then once the GC of the former instance continues its work it will crash because it assumes the flash is enabled but it actually is disabled.
Not sure if I described it clear:) So, please, feel free to ask any questions.

Proposed solution: move [this _enable()](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L269) right [here](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L321) and [this _disable()](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L312) [here](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L322). After these movements, enabling and disabling should become always called together within one synchronous operation. Moreover, the [semaphore](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L69) may be removed after that, I suppose. And all _enable()s and _disable()s may be replaced with simple _flash.enable/disable.

**Comment by alexey-nbl** [comment]
Probably, this is a potential issue even with one instance.

**Comment by ragrus-nbl** [comment]
I think, this shouldn’t occur with one instance due to the counter (semaphore) of enables/disables

**Comment by betzrhodes** [comment]
Fix released in version 3.0.0
