### ISSUE TITLE
Exception: the index 'SPIFLASHFILESYSTEM_ERROR' does not exist

### ISSUE THREAD

**Issue by ragrus-nbl** [electricimp/SPIFlashFileSystem#31]
There is a little bug [here](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L863). `SPIFlashFileSystem.` should be removed.

**Comment by ppetrosh** [comment]
And [here](https://github.com/electricimp/SPIFlashFileSystem/blob/master/SPIFlashFileSystem.device.lib.nut#L769)?

**Comment by ragrus-nbl** [comment]
Yep, you're right!

**Comment by betzrhodes** [comment]
Thanks nice catch. Patch in release v3.0.1.
